language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --no-interaction --dev --prefer-dist
  - ./vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/ ./

script: ./vendor/bin/phpunit --coverage-text
